config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :location
  resources :encounter
  resources :specie
  get "/admin", to: "admin#index"
  get "/admin/csv", to: "admin#upload_csv"
  post "/admin/upload", to: "admin#import_csv#admin"
  get "/admin/success", to: "admin#success"
  get "/playground", to: "location#playground"
  get "/geoapi", to: "location#geo_json_api"
  get "/get_by_state/:state", to: "location#get_by_state"
  get "/get_by_date", to: "encounter#get_by_date"
  get "/get_by_range", to: "encounter#get_by_range"
  get "/get_by_date_api", to: "encounter#get_by_date_api"
  get "/get_by_range_api", to: "encounter#get_by_range_api"
  get "/specie_geo_api", to: "encounter#specie_geo_api"
  get "/my_encounters/:id", to: "encounter#my_encounters"
  get "/user_encounters", to: "encounter#user_encounters"
  get "/get_specie_encounter_graph_api/:specie", to: "encounter#get_encounters_time_graph_api"
  get "/encounter/csv/upload", to: "encounter#csv_upload"
  post "/encounter/csv/import_api", to: "encounter#import_csv"
  get "/encounter/csv/success", to: "encounter#csv_upload_success"
  #V1 Api Routes
  namespace :api do
    namespace :v1 do
      resources :locations
      resources :species
      resources :encounters, only: [:create, :destroy, :update, :show, :index, :destroy]
      resources :sessions, only: [:create, :destroy]
      post "/sessions/authenticate", to: "sessions#authenticate"
      post "/sessions/create_user", to: "sessions#create_user"
      get "/encounters/get_by_date/range", to: "encounters#get_by_date"
      get "/encounters/get_by_month/range", to: "encounters#get_by_month"
      get "/encounters/get_by_specie_and_month/range", to: "encounters#get_by_specie_and_month"
      get "/encounters/user/:user", to: "encounters#get_user_encounters"
      get "/locations/states/all", to: "locations#get_states"
    end
  end
  #Route Route
  root to: "location#index"
end

app/controllers/api/v1/encounters_controller.rb
class Api::V1::EncountersController < ApiController
  before_action :set_encounter, only: [:show, :update]
  before_action :is_authenticated, only: [:create, :update]
  before_action :is_mine, only: [:update]

  def index
    render json: Encounter.all.order("date DESC")
  end

  def show
    render json: @encounter
  end

  def get_by_date
    @encounters = Encounter.date_range(params[:start], params[:end])
    render json: @encounters
  end

  def get_by_month
    @encounters = Encounter.month_range(params[:start], params[:end])
    render json: @encounters
  end

  def get_by_specie_and_month
    @encounters = Encounter.get_by_specie_and_month(params[:start], params[:end], params[:specie_id])
    render json: @encounters
  end

  def get_user_encounters
    @encounters = Encounter.where("user_id = #{params[:user]}")
    render json: @encounters
  end

  def create
    @location = location_create
    if @location != nil
      @specie = specie_create
      if @specie != nil
        begin
          @encounter = Encounter.create(date: Date.parse(params[:date].to_s), description: params[:description], location_id: @location.id, specie_id: @specie.id, user_id: @user.id)
          if @encounter.save
            render json: @encounter
          else
            render json: @encounter.errors
          end
        rescue StandardError => e
          render json: { errors: ["Must enter in a valid date in the correct format. Ex: 5th May 2016", e.backtrace ] }
        end
      end
    end
  end

  def update
    @location = location_create
    if @location != nil
      @specie = specie_create
      if @specie != nil
        if @encounter.update_attributes(encounter_params)
          @encounter.update_attribute("specie_id",@specie.id)
          @encounter.update_attribute("location_id",@location.id)
          render json: @encounter
        else
          render json: { errors: @encounters.errors }
        end
      end
    end
  end

  private
    #Location and Specie Create Helper Methods
    def location_create
      edit_location = false
      Location.all.each do |l|
        edit_location = true if l.title != params[:title] && l.address == params[:address] && l.state == params[:state] && l.city == params[:city] && l.country == params[:country]
      end
      if !edit_location
        @location = Location.create(address: params[:address],city: params[:city], state: params[:state], country: params[:country], user_id: @user.id, title: params[:title])
        if @location.save
          return @location
        else
          if @location.errors.values.first.first == "This location already exists"
             @location = Location.where("city = '#{params[:city]}' AND address = '#{params[:address]}' And state = '#{params[:state]}'").first
             return @location
          else
            render json: {errors: @location.errors}
            return nil
          end
        end
      else
        @location = Location.where("city = '#{params[:city]}' AND address = '#{params[:address]}' And state = '#{params[:state]}'").first
        if @location != nil && @location.update_attribute("title", params[:title])
          return @location
        else
          if @location != nil
            render json: {errors: @location.errors}
          else
            render json: {errors: "This is not a valid location."}
          end
          return nil
        end
      end
    end
    def specie_create
      puts "Error Found: #{params[:toggleSpecie] == nil}"
      if params[:toggleSpecie]
        @specie = Specie.create(common: params[:common], scientific: params[:scientific], user_id: @user.id)
        if @specie.save
          return @specie
        else
          if @specie.errors.values.first.first == "This specie is already in our system."
            return Specie.where("common = '#{params[:common]}' AND scientific = '#{params[:scientific]}'").first
          else
            render json: { errors: @specie.errors }
            return nil
          end
        end
      else
        @specie = Specie.find(params[:specie])
        if @specie != nil
         return @specie
        else
          render json: { errors: ["Could Not Find Species"]}
        end
      end
    end

    #Before Actions and Params

    def encounter_params
      { description: params[:description]}
    end

    def set_encounter
      @encounter = Encounter.find(params[:id])
    end

    def is_authenticated
      if !User.authenticate_via_token params[:email], params[:token]
        head(:unauthorized)
      else
        @user = User.where("email = '#{params[:email]}'").first
      end
    end

    def is_mine
      puts "User #{@user.id} Encounter #{@encounter.user_id}"
      if !@user.is_mine @encounter
        head(:unauthorized)
      end
    end
end

app/controllers/encounter_controller.rb
class EncounterController < ActionController::Base
  protect_from_forgery with: :exception
  layout "application"
  before_action :set_encounter, only: [:show,:edit,:update,:destroy]
  before_action :is_signed_in, only: [:new,:edit,:create,:update,:my_encounters, :delete]
  before_action :authorized, only: [:edit,:update, :delete]
  def show
    @location = Location.find(@encounter.location_id)
    @user = @encounter.user_id ? User.find(@encounter.user_id) : nil
    @specie = Specie.find(@encounter.specie_id)
  end
  def new
    @address = params[:address]
    @city = params[:city]
    @state = params[:state]
    @country = params[:country]
  end
  def create
    return_path = new_encounter_path
    @location = location_create return_path
    if @location != nil
      @specie = specie_create return_path
      if @specie != nil
        begin
          @encounter = Encounter.create(date: Date.parse(params[:date]), description: params[:description], location_id: @location.id, specie_id: @specie.id, user_id: current_user.id)
          if @encounter.save
            redirect_to encounter_path(@encounter.id), alert: "Successfully created encounter."
          else
            redirect_to return_path, alert: @encounter.errors.values.first.first
          end
        rescue
          redirect_to return_path, alert: "Must enter in a valid date in the correct format. MM/DD/YYYY."
        end
      end
    end
  end
  def edit
    @location = Location.find(@encounter.location_id)
    @specie = Specie.find(@encounter.specie_id)
  end
  def destroy 
    if @encounter.destroy!
      redirect_to location_index_path, alert: "Succesfully deleted encounter!"
    else  
      redirect_to location_index_path, alert: "There was an issue deleting the encounter."
    end
  end
  def update
    return_path = edit_encounter_path(id: @encounter.id)
    @location = location_create return_path
    if @location != nil
      @specie = specie_create return_path
      if @specie != nil
        if @encounter.update_attributes(encounter_params)
          @encounter.update_attribute("specie_id",@specie.id)
          @encounter.update_attribute("location_id",@location.id)
          redirect_to encounter_path(@encounter.id), alert: "The encounter has been updated successfully."
        else
          redirect_to edit_encounter_path(return_path), alert: @encounter.errors.values.first.first
        end
      end
    end
  end
  def my_encounters
    @encounters = Encounter.where("user_id = #{current_user.id}")
  end
  def user_encounters
    @user = User.find(params[:user])
    @encounters = Encounter.where("user_id = #{params[:user]}")
  end
  def get_by_date
    @date = params[:date]
    @encounters = Encounter.where("date = '#{params[:date]}'")
  end
  def get_by_range
    @start = params[:start]
    @end = params[:end]
    @encounters = Encounter.date_range(params[:start],params[:end])
    @month = (@encounters.first.get_month[:start].to_s == @start && @encounters.first.get_month[:end].to_s == @end) ? "#{@start.split('-')[1]}/#{@start.split('-')[0]}" : false
  end
  def location_create return_path
    @location = Location.create(address: params[:address],city: params[:city], state: params[:state], country: params[:country], user_id: current_user.id)
    if @location.save
      return @location
    else
      if @location.errors.values.first.first == "This location already exists"
         @location = Location.where("city = '#{params[:city]}' AND address = '#{params[:address]}' And state = '#{params[:state]}'").first
         return @location
      else
        redirect_to return_path, alert: @location.errors.values.first.first
        return nil
      end
    end
  end
  def specie_create return_path
    puts "Error Found: #{params[:toggleSpecie] == nil}"
    if params[:toggleSpecie] != nil
      @specie = Specie.create(common: params[:common], scientific: params[:scientific], user_id: current_user.id)
      if @specie.save
        return @specie
      else
        if @specie.errors.values.first.first == "This specie is already in our system."
          return Specie.where("common = '#{params[:common]}' AND scientific = '#{params[:scientific]}'").first
        else
          redirect_to return_path, alert: @specie.errors.values.first.first
          return nil
        end
      end
    else
      @specie = Specie.find(params[:specie])
      if @specie != nil
       return @specie
      else
        redirect_to return_path, alert: "Could not find species."
      end
    end
  end
  def get_by_date_api
    @encounters = Encounter.date_range(params[:date],params[:date])
    render json: @encounters
  end
  def get_by_range_api
    @encounters = Encounter.date_range(params[:start],params[:end])
    render json: @encounters
  end
  def specie_geo_api
    @encounters = Encounter.find_by_sql("SELECT l.latitude, l.longitude, l.city, l.state, l.address, l.title, e.location_id, l.country, l.slug, CONCAT(l.city, ', ', l.state, ', ', l.country) as full_address FROM encounters e JOIN species s ON e.specie_id = s.id JOIN locations l ON l.id = e.location_id WHERE e.specie_id = '#{params[:specie]}' GROUP BY e.location_id, l.latitude, l.longitude, l.city, l.state, l.address, l.title, l.country, l.slug") 
    render json: @encounters
  end
  def get_encounters_time_graph_api
    @encounters = Encounter.find_by_sql("SELECT date_part('month', date) as month, COUNT(id) as encounter_count FROM encounters WHERE specie_id = #{params[:specie]} GROUP BY date_part('month', date) ORDER BY month ASC")
    render json:  @encounters
  end

  def csv_upload

  end

  def import_csv
    file = params[:file]
    months = ["January","February","March","April","May","June","July","August","September","October","November","December"]
    species = []
    encounters = []
    locations = []
    first = true
    successes = 0
    rows = 0
    errors = []
    begin
      CSV.foreach(file.path, headers: true) do |row|
        begin
          if !first
            cell = row[2]
            rows += 1
            location = ""
            date = ""
            monthFormat = false
            months.each do |month|
              if cell.include? month
                vals = cell.split(month)
                location = vals[0]
                date = month + vals[1]
                monthFormat = true
              end
            end
            if !monthFormat
              firstStr = false
              segs = cell.split("/")
              month = months[segs[0].split(" ").last.to_i]
              day = segs[1]
              year = segs[2]
              date = [month,day,year].join(" ")
              temp = segs[0].split(" ")
              temp.pop
              fin = temp.join(" ")
              location = fin
            end
            found = false
            x = { common_name: row[0], scientific_name: row[1] }
            species.each do |specie|
              found = true if x == specie
            end
            Specie.all.each do |specie|
              found = true if x[:scientific_name] == specie.scientific || x[:common_name] == specie.common
            end
            exists = false
            l = location.split(",").length == 3 ? { city: location.split(",")[2].strip, state: location.split(",")[0].strip, country: "United States of America" } : { city: location.split(",")[3].strip, state: location.split(",")[1].strip, country: location.split(",")[0].strip }
            locations.each do |location|
              exists = true if l[:city].strip == location[:city].strip && location[:state] == l[:state].strip
            end
            Location.all.each do |location|
              exists = true if l[:city].strip == location.city.strip && location[:state] == l[:state].strip
            end
            e = { observations: row[3], date: date, location: l, specie: x }
            species.push(x) if !found || species.length + Specie.all.length == 0
            encounters.push(e)
            locations.push(l) if (!exists || locations.length + Location.all.length == 0)
        else
          first = false
        end
      rescue Exception => e
        puts "Error Message: #{e.message} - #{e.backtrace.inspect}"
        errors.push({ error: "The following row is formatted incorrectly.", row: row})
        puts "Error Found: #{row}"
      end
      end
    rescue Exception => e  
      puts "CSV Error: #{e}"
      errors.push({ error: "You must provide a valid CSV.", row: -1})
    end
    locations.each do |l|
      begin 
        Location.create!(city: l[:city], state: l[:state], title: "Untitled", country: l[:country], address: "", user_id: 1)
      rescue Exception => e  
        puts "Location already exists: #{l[:city]}"
      end
    end
    species.each do |s,i|
      begin 
        Specie.create!(scientific: s[:scientific_name], common: s[:common_name])
      rescue Exception => e  
        puts "Specie already exists: #{s[:common_name]}"
      end
    end
    encounters.each do |e,i|
      loco = Location.where("city like '%#{e[:location][:city]}%'").first
      spec = Specie.where("scientific='#{e[:specie][:scientific_name]}'")
      if spec.length == 0
        spec = Specie.where("common='#{e[:specie][:common_name]}'")
      end
      spec = spec.first.id
      dupes = Encounter.all.to_a.rindex { |n| n.description == e[:observations] && n.specie_id = spec }
      if dupes == nil
        begin
          loco.encounters.create!(description: e[:observations], date: e[:date], specie_id: spec)
        rescue Exception => error_message  
          errors.push({ error: "The following encounter is not formatted correctly.", row: e.to_s})
        end
        successes += 1
      else  
        errors.push({ error: "The following row is a duplicate encounter.", row: e.to_s})
      end
    end

app/views/encounter/_table.html.erb
<% if encounters.length > 0 %>
  <div class="list" id="encounter">
    <input type="text" id="encounterSearch" placeholder="Search" style="width: calc(100% - 100px); margin: 20px;"/>
    <p id="encounterSearchResults" style="display: none; margin: 20px; padding-bottom: 20px;">Sorry, there are no search results.</p>
    <div class="list__pagination">
      <div class="list__pages" id="encounterPages">
      </div>
      <label for="encounterPageQuantitySelector">Encounters/Page</label>
      <select id="encounterPageQuantitySelector">
        <option default>25</option>
        <option>50</option>
        <option>75</option>
        <option>100</option>
      </select>
      <div class="list__total-pages"></div>
    </div>
    <% encounters.each do |e| %>
      <a class="list-item" href="<%= encounter_path(e.slug) %>">
        <img src="https://www.bio-techfar.com/images/assets/leaf.png" />
        <div class="list-item__text-group">
          <div class="list-item__text-group__title">
            <%= (e["common"] != nil) ? e.common : e.description %>
          </div>
          <div class="list-item__text-group__sub-title">
            <%= e.date %>
          </div>
        </div>
      </a>
    <% end %>
  </div>

  <script>
    const encounterSearch =  document.getElementById("encounterSearch");
    let pageLimit = 25;
    let currentPage = 0;
    let currentPageShift = 0;
    const paginationDiv = document.querySelector(".list__pagination");
    const totalPagesDiv = document.querySelector(".list__total-pages");

    window.onresize = () => {
      filterAndPaginate();
    }

    const filterEncounterResults = () => {
      let resultCount = 0;
      document.querySelectorAll(".list-item").forEach((l) => {
        l.style.display = "block";
      });
      document.querySelectorAll(".list-item").forEach((l) => {
        if(l.innerHTML.indexOf("bio-techfar") != -1){
          if(l.innerHTML.toLowerCase().indexOf(encounterSearch.value.toLowerCase()) != -1 && encounterSearch.value != ""){
            l.style["display"] =  "block";
            resultCount++;
          }else if(encounterSearch.value != ""){
              l.style["display"] =  "none";
          }else{
              resultCount++;
              l.style["display"] =  "block";
          }
        }
      });
      const searchResults = document.getElementById("encounterSearchResults");
      if(resultCount === 0){
        searchResults.style.display = "block";
        paginationDiv.style.display = "none";
      }else{
        searchResults.style.display = "none";
        paginationDiv.style.display = window.innerWidth > 600 ? "flex" : "grid";
      }
    }

    

    const paginateResults = () => {
      let searchCount = 0;
      document.querySelectorAll(".list-item").forEach((sr) => {
        if(sr.innerHTML.indexOf("bio-techfar") != -1){
          if(sr.style.display == "block"){
            searchCount++;
            if(searchCount > pageLimit+currentPage*pageLimit || searchCount < currentPage*pageLimit){
              sr.style.display = "none";
            }
          }
        }
      });
      const realTotalPages = Math.ceil(searchCount/pageLimit);
      const totalPages = realTotalPages-currentPageShift*5 < 5 ? realTotalPages-currentPageShift*5 : 5;
      const pageButtons = ["<"];
      totalPagesDiv.innerHTML = "Current Page: "+(currentPage+1)+"/"+realTotalPages;
      for(let i = 0; i < totalPages; i++){
        pageButtons.push(i+1+5*currentPageShift);
      }
      pageButtons.push(">");
      
      const paginationPages = document.querySelector(".list__pages");
      paginationPages.innerHTML = "";
      pageButtons.forEach((b, i) => {
        const myDiv = document.createElement("div");
        myDiv.innerHTML = b;
        myDiv.className = "list__pages__page";
        myDiv.addEventListener("click", () => {
          if(parseInt(b) > 0) {
            currentPage = i - 1 + (5*currentPageShift);
          }else if(b == "<"){
            shiftPages(-1);
          }else{
            shiftPages(1);
          }
          filterAndPaginate();
        });
        if(i - 1 == currentPage && parseInt(b) > 0){
          myDiv.className += " selected-page";
        }
        paginationPages.append(myDiv);
      });
    }

    const shiftPages = (direction) => {
      currentPageShift += direction;
      const maxPageShift = Math.floor(parseInt(totalPagesDiv.innerHTML.split("/")[1])/5);
      if(currentPageShift < 0){
        currentPageShift = 0;
      }else if(currentPageShift > maxPageShift){
        currentPageShift = maxPageShift;
      }
      filterAndPaginate();
    }

    const filterAndPaginate = () => {
      filterEncounterResults();
      paginateResults();
    }

 

    window.onload = () => {
      window.onload();
      filterEncounterResults();
      paginateResults();
    }
    filterEncounterResults();
    paginateResults();
    const quantitySelector = document.getElementById("encounterPageQuantitySelector");
    quantitySelector.addEventListener("change", (e) => {
      pageLimit = parseInt(e.target.value);
      currentPage = 0;
      currentPageShift = 0;
      filterAndPaginate();
    });
    encounterSearch.addEventListener("keyup", () => {
      filterAndPaginate()
      currentPage = 0;
      currentPageShift = 0;
    });
  </script>
<% else %>
  <div class="list" id="encounter">
    <h4 style="padding: 20px">Sorry, but there are no encounters available.</h4>
  </div>
<% end %>

app/views/encounter/_time_graph.html.erb
<div class="time-graph">
    <div class="time-graph__title"><%= title %></div>
    <div class="time-graph__bars">
        <% max_blocks = months.sort { |x,y| y[:encounter_count] <=> x[:encounter_count] }.first[:encounter_count] %>
        <% block_height = max_blocks > 0 ? (300/max_blocks).ceil : 50 %>
        <% months.each do |m| %>
            <div class="time-graph__bars__bar" style="height: <%=(m[:encounter_count]).floor*block_height%>px">
                <div class="time-graph__bars__bar__bubble">
                    <%= "#{m[:encounter_count]} encounter#{m[:encounter_count] > 1 ? 's' : ''} in #{Date::MONTHNAMES[m[:month]]}." %>
                    <div class="time-graph__bars__bar__bubble__carot"></div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="time-graph__legend">
        <% months.each do |m| %>
            <div class="time-graph__legend__month">
                <%= Date::ABBR_MONTHNAMES[m[:month]] %>
            </div>
        <% end %>
    </div>
</div>

app/views/encounter/csv_upload.html.erb
<div class="content-card">
  <h1>Import Encounters Into The System By Uploading a CSV</h1>
  <hr>
  <p>A CSV is a file that can be exported from spreadsheet applications such as Google Sheets and Microsoft Excel. Encounters can be uploaded by community members to the system using this form. The form requires that the spreadsheet used to produce the CSV follows the following format. The spreadsheet must contain a header row with the following cells 'Common Name', 'Scientific Name', 'Location' and 'Observations'. The cells must be in this order. Each row following the header row corresponds to an encounter. Each of these rows must be formatted in the following manner.</p>
  <table>
    <thead> 
      <tr>
        <th colspan="2">Encounter Row Cell Formatting</th>
      </tr>
      <tr>
        <th>Cell</th>
        <th>Structure<th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Common Name</td>
        <td>Any string of chararacters. Example: Sugar Maple</td>
      </tr>
      <tr>
        <td>Scientific Name</td>
        <td>Any string of chararacters. Example: <i>Acer saccharum</i></td>
      </tr>
      <tr>
        <td>Location</td>
        <td>One of the following four formats 
          <ul style="margin-top: 0px;">
            <li>State, County, City Month-Name Date Year Example: Utah, Utah Co., Orem September 18 2015</li>
            <li>State, County, City Month-Number/Date/Year Example: Utah, Utah Co., Orem 09/18/2015</li>
            <li>Country, State, County, City Month-Name Date Year Example: United States of America, Utah, Utah Co., Orem September 18 2015</li>
            <li>Country, State, County, City Month-Number/Date/Year Example: United States of America, Utah, Utah Co., Orem 09/18/2015</li>
          </ul>
          *If no country is supplied it is assumed that the encounter occured within the United States
        </td>
      </tr>
      <tr>
        <td>Observations</td>
        <td>Any string of characters. Example: I found this tree at the Orem City Aboretum.</td>
      </tr>
    </tbody>
  </table>
  <%= form_tag("/encounter/csv/import_api", method: "post", :multipart => true) do %>
    <label for="file">CSV File Selector</label>
    <%= file_field_tag :file, style: "border: none;" %>
    <%= submit_tag "Upload", class: "green-button", style: "display: block; margin-top: 20px;" %>
  <% end %>
</div>

app/views/encounter/csv_upload_success.html.erb
<div class="content-card">
  <% if @errors.first[:row].to_i != -1 %>
    <h1>The CSV Upload Form Was Submitted Successfully!</h1>
    <p>Thank you for your contribution.</p>
  <% else %>
    <h1>The file you uploaded is not a properly formatted CSV.</h1>
    <p>Please try again with a properly formatted file.</p>
  <% end %>
  <%= "<p>The following rows had issues that prevented them from being uploaded.</p>".html_safe if @errors && @errors.length > 0 && @errors.first[:row].to_i != -1 %>
  <ul>
    <% if @errors && @errors.first[:row].to_i != -1  %>
      <% @errors.each do |e| %>
        <li><%= e[:error] %>
          <% if e[:row].split("=>").length > 1 %> 
            <table>
              <thead>
                <tr>
                  <% eval(e[:row]).keys.each do |k| %>
                    <th><%= k %></th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% eval(e[:row]).values.each do |v| %>
                    <% if v.instance_of? Hash%>
                      <td><%= v.values.join(", ")%></td>
                    <% else %>
                      <td><%= v %></td>
                    <% end %>
                  <% end %>
                </tr>
              </tbody>
            </table>
          <% else %>
            <% tvalues = [e[:row].split('",')[1], e[:row].split(',"')[1].split('",')[0], e[:row].split(',"')[0]]%>
            <table>
              <thead>
                <tr>
                  <% ['observations', 'date & location', 'specie'].each do |h| %>
                    <th><%= h %></th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% tvalues.each do |v| %>
                    <td><%= v %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
          <% end %>
        </li>
      <% end%>
    <% end %>
  </ul>
  <%= "<p>There are #{@remainder} additional rows with issues.".html_safe if @remainder.to_i > 0 && @errors.first[:row].to_i != -1 %>
</div>

app/views/encounter/get_by_date.html.erb
<div class="content-card">
  <div class="loco-map">
    <h1 class="loco-map-right-title"><%= @date %> Encounters</h1>
    <div id="locoMap"></div>
  </div>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />
  <script>
    const DATE = "<%= @date %>";
  </script>
  <%= javascript_include_tag "dateMap" %>
  <%= render partial: "encounter/table", locals: {encounters: @encounters} %>
  <br />
  <%= back_button({ path: root_path})  %>
</div>

app/views/encounter/get_by_range.html.erb
<div class="content-card">
  <div class="loco-map">
    <h1 class="loco-map-right-title"><%= @month != false ? @month : "#{@start} to #{@end}" %> Encounters</h1>
    <div id="locoMap"></div>
  </div>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />
  <script>
    const START = "<%= @start %>";
    const END = "<%= @end %>";
    const PATH = "<%= get_by_range_api_path(start: @start,end: @end) %>".substring(1);
  </script>
  <%= javascript_include_tag "dateMap" %>
  <%= render partial: "encounter/table", locals: {encounters: @encounters} %>
  <br />
  <%= back_button({ path: root_path})  %>
</div>

app/views/encounter/show.html.erb
<div class="content-card">
  <h1><%= (@encounter.date_occurences == 1) ? @encounter.date : link_to(@encounter.date, get_by_date_path({date: @encounter.date})) %></h1>
  <p><%= link_to "<i class='fas fa-leaf'></i> #{@specie.common}, #{@specie.scientific}".html_safe, specie_path(@specie.slug) %></p>
  <%= link_to "<i class='fas fa-map-marker-alt'></i> #{@location.full_address}".html_safe, location_path(@location.id) %>
  <br />
  <br />
  <%= link_to "<i class='fas fa-calendar-alt'></i> #{@encounter.date.month}/#{@encounter.date.year} Encounters".html_safe, get_by_range_path(@encounter.get_month) %>
  <br />
  <br />
  <%= link_to "<i class='fas fa-search'></i> #{@user.display}".html_safe, user_encounters_path(user: @user.id) if @user %>
  <p><%= link_to "<i class='fas fa-edit'></i> Edit".html_safe, edit_encounter_path if signed_in? && current_user.is_mine(@encounter) %></p>
  <p><%= @encounter.description %></p>
  <%= back_button({ path: location_path(@encounter.location_id)}) %>
</div>