config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :location
  resources :encounter
  resources :specie
  get "/admin", to: "admin#index"
  get "/admin/csv", to: "admin#upload_csv"
  post "/admin/upload", to: "admin#import_csv#admin"
  get "/admin/success", to: "admin#success"
  get "/playground", to: "location#playground"
  get "/geoapi", to: "location#geo_json_api"
  get "/get_by_state/:state", to: "location#get_by_state"
  get "/get_by_date", to: "encounter#get_by_date"
  get "/get_by_range", to: "encounter#get_by_range"
  get "/get_by_date_api", to: "encounter#get_by_date_api"
  get "/get_by_range_api", to: "encounter#get_by_range_api"
  get "/specie_geo_api", to: "encounter#specie_geo_api"
  get "/my_encounters/:id", to: "encounter#my_encounters"
  get "/user_encounters", to: "encounter#user_encounters"
  get "/get_specie_encounter_graph_api/:specie", to: "encounter#get_encounters_time_graph_api"
  get "/encounter/csv/upload", to: "encounter#csv_upload"
  post "/encounter/csv/import_api", to: "encounter#import_csv"
  get "/encounter/csv/success", to: "encounter#csv_upload_success"
  #V1 Api Routes
  namespace :api do
    namespace :v1 do
      resources :locations
      resources :species
      resources :encounters, only: [:create, :destroy, :update, :show, :index, :destroy]
      resources :sessions, only: [:create, :destroy]
      post "/sessions/authenticate", to: "sessions#authenticate"
      post "/sessions/create_user", to: "sessions#create_user"
      get "/encounters/get_by_date/range", to: "encounters#get_by_date"
      get "/encounters/get_by_month/range", to: "encounters#get_by_month"
      get "/encounters/get_by_specie_and_month/range", to: "encounters#get_by_specie_and_month"
      get "/encounters/user/:user", to: "encounters#get_user_encounters"
      get "/locations/states/all", to: "locations#get_states"
    end
  end
  #Route Route
  root to: "location#index"
end

app/models/location.rb
class Location < ApplicationRecord
  extend FriendlyId
  friendly_id :full_address, use: :slugged
  belongs_to :user
  has_many :encounters
  validate :unique_address, :required_fields, :address_exists
  geocoded_by :full_address do |object, results|
    if results.present?
     object.latitude = results.first.latitude
     object.longitude = results.first.longitude
    else
     object.latitude = nil
     object.longitude = nil
    end
  end
  before_validation :geocode
  def full_address
    addressArray = [address, city, state, country]
    addressArray.shift if address == ""
    addressArray.compact.join(", ")
  end
  def safe_title
    if title == "Untitled" || title != ""
      if address == ""
        return city
      else
        return address
      end
    else
      return title
    end
  end
  def unique_address
    Location.all.each do |l|
      errors.add(:address, "This location already exists") if l.full_address == full_address && l.id != id
    end
  end
  def required_fields
    if city == ""
      errors.add(:city, "You must enter in a city.")
    elsif state == ""
      errors.add(:state, "You cannot leave the state blank.")
    elsif country == ""
      errors.add(:country, "You cannot leave the country blank.")
    end
  end
  def address_exists
    errors.add(:address, "This location does not exist.") if latitude == nil
  end
  def self.state str
    geo = Geocoder.search(str).first
    { latitude: geo.latitude, longitude: geo.longitude }
  end
end

app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < ApiController
  before_action :set_location, only: [:show, :update]
  before_action :is_authenticated, only: [:create, :update]
  before_action :is_mine, only: [:update]

  def index
    render json: Location.find_by_sql("SELECT l.*, COUNT(e.id) as pop FROM locations l LEFT JOIN encounters e ON e.location_id = l.id GROUP BY l.id ORDER BY l.state ASC, l.title ASC, l.city ASC").map { |l| {city: l.city, title: l.title, state: l.state, country: l.country, full_address: l.full_address, id: l.id, latitude: l.latitude, longitude: l.longitude, encounters: l.pop} }
  end
  def show
    l = @location
    render json: { city: l.city, full_address: l.full_address, id: l.id, latitude: l.latitude, longitude: l.longitude, encounters: l.encounters, title: l.title, state: l.state, country: l.country }
  end
  def create
    @location = Location.new(location_params)
    if @location.save
      render json: @location
    else
      render json: { errors: @location.errors}
    end
  end
  def update
    if @location.update_attributes(location_params)
      render json: @location
    else
      render json: {errors: @location.errors}
    end
  end
  def get_states
    render json: Location.find_by_sql("SELECT DISTINCT state FROM locations").map { |l| l.state }
  end

  private
    def location_params
      params.permit(:title,:address,:city,:state,:country,:user_id)
    end

    def set_location
      @location = Location.find(params[:id])
    end

    def is_authenticated
      if !User.authenticate_via_token params[:email], params[:token]
        head(:unauthorized)
      else
        @user = User.where("email = '#{params[:email]}'").first
      end
    end

    def is_mine
      if !@user.is_mine @location
        head(:unauthorized)
      end
    end
end

app/controllers/location_controller.rb
class LocationController < ActionController::Base
  protect_from_forgery with: :exception
  layout "application"
  def index
    @locations = Location.find_by_sql("SELECT l.* FROM locations l LEFT JOIN encounters e ON e.location_id = l.id GROUP BY l.id HAVING COUNT(e.id) > 0 ORDER BY ASCII(city)+ASCII(state)*10 ASC")
  end
  def show
    @location = Location.friendly.find(params[:id])
    @encounters = Encounter.find_by_sql("SELECT e.*, s.common FROM encounters e JOIN species s ON e.specie_id = s.id WHERE e.location_id = #{@location.id.to_s} ORDER BY e.date DESC")
    @months = Encounter.get_time_graph('location', @location.id.to_s)
  end
  def playground

  end
  def geo_json_api
    render json: Location.find_by_sql("SELECT l.*, COUNT(e.id) as pop FROM locations l LEFT JOIN encounters e ON e.location_id = l.id GROUP BY l.id HAVING COUNT(e.id) > 0").map { |l| {city: l.city, full_address: l.full_address, id: l.id, latitude: l.latitude, longitude: l.longitude, encounters: l.pop, slug: l.slug} }
  end
  def get_by_state
    @locations = Location.where("state = '#{params[:state]}'").joins(:encounters).group('encounters.location_id, locations.id').having("COUNT(encounters.id) > 0").order("city ASC")
    @months = Encounter.get_time_graph('state', params[:state])
    @state = State.where("name = '#{params[:state]}'").first
  end
end

app/helpers/v1/locations_helper.rb
module V1::LocationsHelper
end

app/views/location/_table.html.erb
<% if locations.length > 0 %>
  <div class="list">
    <input type="text" id="locationSearch" placeholder="Search" style="width: calc(100% - 100px); margin: 20px;"/>
    <p id="locationSearchResults" style="display: none; margin: 20px; padding-bottom: 20px;">Sorry, there are no search results.</p>
    <% locations.each do |l| %>
      <a class="list-item" href="<%= location_path(l.slug) %>">
        <%= image_tag "pin" %>
        <p><%= l.full_address %></p>
      </a>
    <% end %>
  </div>
  <script>
    const locationSearch =  document.getElementById("locationSearch");

    const filterResults = () => {
      let results = 0;
      document.querySelectorAll(".list-item").forEach((l) => {
        if(l.innerHTML.indexOf("pin") != -1){
          if(l.innerHTML.toLowerCase().indexOf(locationSearch.value.toLowerCase()) != -1 && locationSearch.value != ""){
            l.style["display"] =  "block";
            results++;
          }else if(locationSearch.value != ""){
              l.style["display"] =  "none";
          }else{
              l.style["display"] =  "block";
              results++;
          }
        }
        const locationSearchResults = document.getElementById("locationSearchResults");
        if(results === 0){
          locationSearchResults.style.display = "block";
        }else{
          locationSearchResults.style.display = "none";
        }
      });
    }

    window.onload = () => {
      window.onload();
      filterEncounterResults();
    }

    locationSearch.addEventListener("keyup", () => filterResults());
  </script>
<% else %>
  <div class="list" id="encounter">
    <h4 style="padding: 20px">Sorry, but there are no locations available.</h4>
  </div>
<% end %>

app/views/location/get_by_specie.html.erb
<div class="content-card">
  <h1>Locations for <%= @specie.common %></h1>
  <%= render partial: "location/table", locals: {locations: @locations} %>
  <br />
  <%= back_button({path: root_path}) %>
</div>

app/views/location/get_by_state.html.erb
<div class="content-card">
  <div class="loco-map">
    <h1 class="loco-map-title">Locations for <%= params[:state] %></h1>
    <div class="loco-map-mask"></div>
    <div id="locoMap"></div>
  </div>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />
  <script>
    const LOCATION = [<%= @state ? @state.latitude : Location.state(params[:state])[:latitude] %>, <%= @state ? @state.longitude : Location.state(params[:state])[:longitude] %>];
    const ZOOM = 6;
  </script>
  <%= javascript_include_tag 'locationMap' %>
  <%= render partial: "location/table", locals: {locations: @locations} %>
  <br />
  <%= render partial: "encounter/time_graph", locals: {title: "Encounters For #{params[:state]} By Month", months: @months } %>
  <%= back_button({path: root_path}) %>
</div>

app/views/location/index.html.erb
<div class="content-card">
  <h1>Locations</h1>
  <div id="map"></div>
  <%= link_to "<i class='fas fa-plus''></i>".html_safe, new_encounter_path, class: "round-button", style: "margin-top: 20px; margin-left: 20px;" if signed_in?%>
  <%= "<span>Create Encounter</span>".html_safe if signed_in? %>
  <%= render partial: "location/table", locals: {locations: @locations} %>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />
  <%= javascript_include_tag 'map' %>
</div>

app/views/location/playground.html.erb
<div class="container">
  <h1>Playground</h1>
  <form>
    <label for="delivery_option" >Shipping Option</label>
    <select name="delivery_option">
      <optgroup label="Business">
        <option id="biz_ground">Ground</option>
        <option id="biz_over">Overnight</option>
      </optgroup>
      <optgroup label="Residential">
        <option id="res_ground">Ground</option>
        <option id="res_over">Overnight</option>
      </optgroup>
    </select>
    <hr />
    <label for="delivery">Delivery Preference</label>
    <br />
    <input type="radio" name="delivery" value="pickup" /> Pickup  <br />
    <input type="radio" name="delivery" value="shipping" /> Delivery <br />
  </form>
  <p>Ampersand: &amp;</p>
  <p>Copyright: &copy;</p>
  <p>Trademark: &reg;</p>
  <p>Spaces:     &nbsp;Hello World</p>
  <p>Greater Than: &gt;</p>
  <p>Less Than: &lt;</p>
  <p>Double Qoutes: &quot;</p>
  <p>Single Qoutes: &apos;</p>
  <button class="green-button">Green Button</button>
  <div class="car-maserati"></div>
  <div class="car-tesla"></div>
  <div class="car-porsche"></div>
</div>

app/views/location/show.html.erb
<div class="content-card">
  <div class="loco-map">
    <h1 class="loco-map-title">Encounters for <%= @location.safe_title %></h1>
    <div class="loco-map-mask"></div>
    <div id="locoMap"></div>
  </div>
  <p><%= @location.full_address %></p>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />
  <script>
    const LOCATION = [<%= @location.latitude %>, <%= @location.longitude %>];
    const ZOOM = 10;
  </script>
  <%= javascript_include_tag 'locationMap' %>
  <%= link_to "<i class='fas fa-map-marked'></i> View all encounters in #{@location.state}.".html_safe, "/get_by_state/"+URI.encode(@location.state) %>
  <% if user_signed_in? %>
    <p>
      Create New Encounter
      <%= link_to "<i class='fas fa-plus'></i>".html_safe, new_encounter_path(address: @location.address, city: @location.city, state: @location.state, country: @location.country), class: 'round-button'%>
    </p>
  <% end %>
  <h3>Encounters</h3>
  <%= @encounters.length != 0 ? (render(partial: "encounter/table", locals: {encounters: @encounters})) : "<p>Sorry, there are currently no encounters for this location.</p>".html_safe %>
  <br />
  <%= render partial: "encounter/time_graph", locals: {title: "Encounters For #{@location.safe_title } By Month", months: @months } %>
  <%= back_button({path: root_path}) %></h1>
</div>