config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :location
  resources :encounter
  resources :specie
  get "/admin", to: "admin#index"
  get "/admin/csv", to: "admin#upload_csv"
  post "/admin/upload", to: "admin#import_csv#admin"
  get "/admin/success", to: "admin#success"
  get "/playground", to: "location#playground"
  get "/geoapi", to: "location#geo_json_api"
  get "/get_by_state/:state", to: "location#get_by_state"
  get "/get_by_date", to: "encounter#get_by_date"
  get "/get_by_range", to: "encounter#get_by_range"
  get "/get_by_date_api", to: "encounter#get_by_date_api"
  get "/get_by_range_api", to: "encounter#get_by_range_api"
  get "/specie_geo_api", to: "encounter#specie_geo_api"
  get "/my_encounters/:id", to: "encounter#my_encounters"
  get "/user_encounters", to: "encounter#user_encounters"
  get "/get_specie_encounter_graph_api/:specie", to: "encounter#get_encounters_time_graph_api"
  get "/encounter/csv/upload", to: "encounter#csv_upload"
  post "/encounter/csv/import_api", to: "encounter#import_csv"
  get "/encounter/csv/success", to: "encounter#csv_upload_success"
  #V1 Api Routes
  namespace :api do
    namespace :v1 do
      resources :locations
      resources :species
      resources :encounters, only: [:create, :destroy, :update, :show, :index, :destroy]
      resources :sessions, only: [:create, :destroy]
      post "/sessions/authenticate", to: "sessions#authenticate"
      post "/sessions/create_user", to: "sessions#create_user"
      get "/encounters/get_by_date/range", to: "encounters#get_by_date"
      get "/encounters/get_by_month/range", to: "encounters#get_by_month"
      get "/encounters/get_by_specie_and_month/range", to: "encounters#get_by_specie_and_month"
      get "/encounters/user/:user", to: "encounters#get_user_encounters"
      get "/locations/states/all", to: "locations#get_states"
    end
  end
  #Route Route
  root to: "location#index"
end

app/views/sharred/_alert.html.erb
<div class="alert">
  <div class="alert__header">
    <div class="alert__title">Alert</div>
    <button class="alert__dismiss">x</button>
  </div>
  <div class="alert__content">
    <%= alert %>
    <%= notice %>
  </div>
</div>

app/views/sharred/_footer.html.erb
<footer>
  <div class="footer-section">
    <div class="emphasis">Usefull Links</div>
    <a href="https://github.com/prettygoodstudios/BioEncounters">Github Repo</a>
    <%= link_to "Community CSV Upload", encounter_csv_upload_path %>
    <%= link_to "Admin", admin_path if signed_in? && current_user.role == "admin" %>
  </div>
  <div class="footer-section">
    <%= link_to "<span>Bio</span>Vision".html_safe, root_path, class: "footer-title" %>
  </div>
  <div class="footer-section">
    <div><span class="emphasis">< /></span> with <span class="emphasis"><i class="fas fa-heart"></i></span> by <span class="emphasis">Miguel Rust</span> in <span class="emphasis">Utah.</span></div>
  </div>
</footer>

app/views/sharred/_nav.html.erb
<nav>
  <div class="nav-title-group">
    <div class="toggle-wrapper">
      <button id="toggle" class="toggle toggle__open">
        <div class="toggle-one"></div>
        <div class="toggle-two"></div>
        <div class="toggle-three"></div>
      </button>
    </div>
    <h1><%= link_to "<span>Bio</span>Vision".html_safe, root_path %></h1>
  </div>
  <div class="menu menu__hide">
    <div class="menu-item">
      <%= link_to "Species", specie_index_path %>
    </div>
    <% if current_user == nil %>
      <div class="menu-item"><%= link_to "Sign In", new_user_session_path %></div>
      <div class="menu-item"><%= link_to "Sign Up", new_user_registration_path%></div>
    <% else %>
      <div class="menu-item menu-profile">
        <div class="menu-profile-header">
          <div><%= current_user.display %></div>
          <div>
            <i class="fas fa-user-circle"></i>
            <span class="menu-profile-header__carot"></span>
          </div>
        </div>
        <div class="menu-profile-items">
          <%= link_to "Sign Out <i class='fas fa-sign-out-alt'></i>".html_safe, destroy_user_session_path, method: :delete, class: "menu-profile-item" %>
          <%= link_to "My Encounters <i class='fas fa-leaf'></i>".html_safe, root_url+"my_encounters/"+current_user.id.to_s, class: "menu-profile-item" %>
        </div>
      </div>
    <% end %>
  </div>
</nav>